@connecto.server_HostAddress = http://localhost:5043

POST {{connecto.server_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123"
}

###

POST {{connecto.server_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123",
  "firstName": "Test",
  "lastName": "User"
}

###
